# lexicon: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 '\":-,–;"
lexicon: "abcdefg" # todo: lexicon wrong word
k_factor: 3 # larger = order of magnitude more memory usage, and faster responses
quorum: 1 # writes require acks from <quorum> nodes
replication_factor: 1 # spread data across <replication_factor> nodes
zone: 1 # for topology aware spreads
nodes:
- http://127.0.0.1:8000
- http://127.0.0.1:8001
# - http://127.0.0.1:8002
# - http://127.0.0.1:8003
vnodes_per_node: 10 # number of virtual_nodes. increase for smaller shards
heartbeat_interval: 5 # gossip every <heartbeat_interval> seconds